# Generated by Django 5.1 on 2026-05-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_academicyear_graduation_date'),
        ('examination', '0003_seed_grade_scales'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationlisthandler',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Term this exam belongs to. Used to aggregate marks for term results.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='administration.term'),
        ),
    ]
