# Generated by Django 5.1 on 2026-05-01 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_alter_student_date_of_birth'),
        ('administration', '0005_remove_academicyear_graduation_date'),
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedsubject',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text="Coefficient applied to this subject's average when computing the term general average.", max_digits=4),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='grade_scale',
            field=models.ForeignKey(blank=True, help_text='Grading scale used for this level (e.g., /10 for primary, /20 for college/high-school).', null=True, on_delete=django.db.models.deletion.PROTECT, to='examination.gradescale'),
        ),
        migrations.AlterField(
            model_name='allocatedsubject',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term'),
        ),
        migrations.AlterUniqueTogether(
            name='allocatedsubject',
            unique_together={('teacher_name', 'subject', 'academic_year', 'term', 'class_room')},
        ),
    ]
